### ISSUE TITLE
Skylight unable to start

### ISSUE THREAD

**Issue by danieljacobarcher** [skylightio/skylight-ruby#46]
Getting this error:
````
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision.', ../src/libcore/result.rs:732
[SKYLIGHT] internal error: called `Result::unwrap()` on an `Err` value: A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision.
[SKYLIGHT] [0.8.0] Unable to start
````

**Comment by carllerche** [comment]
Hey there,

Are you per chance running on a beta version of OS X? Could you send an email to support@skylight.io so that we can help you out directly?

**Comment by courtsimas** [comment]
I got the same issue. Using puma. Not on a beta OS X.

**Comment by travisp** [comment]
This happens for me on OS X Yosemite, on puma and other web servers. It does run fine on heroku, but I get this error when I try to run locally to test changes.

**Comment by emilkarl** [comment]
Same here after upgrading to Xcode 7.0 when starting `rails s`

```text
task '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision.', /Users/rustbuild/src/rust-buildbot/slave/nightly-mac/build/src/libcore/result.rs:787
[SKYLIGHT] internal error: called `Result::unwrap()` on an `Err` value: A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision.```

**Comment by DanielWright** [comment]
I'm experiencing a similar issue (Yosemite, Xcode 7.0):

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision.', ../src/libcore/result.rs:732
[SKYLIGHT] internal error: called `Result::unwrap()` on an `Err` value: A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision.
```

**Comment by hsluo** [comment]
same here.
ruby 2.2.3, RVM 1.26.11, OS X 10.10.5

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision.', ../src/libcore/result.rs:732
[SKYLIGHT] internal error: called `Result::unwrap()` on an `Err` value: A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision.
```

**Comment by alexcrichton** [comment]
I believe the source of this bug was in the [curl-rust](https://github.com/carllerche/curl-rust) library being used to make HTTP requests in Rust, and this [also came up in Cargo recently](https://github.com/rust-lang/cargo/issues/1937) (another Rust project using curl-rust), and I think I've [fixed this](https://github.com/carllerche/curl-rust/commit/b4cb511d50f4dabce9fe5ea1d0112c34868b0923) in curl-rust so once skylight upgrades this library it should fix the problem!

**Comment by sergiotapia** [comment]
This is causing us major issues, we can't even migrate our database.

**Comment by alexcrichton** [comment]
@sergiotapia one temporary solution mentioned in was to temporarily remove the `/etc/ssl/certs` directory, does that exist for you and if you move it to a different location does everything progress as usual? (not sure, it may not work!)

**Comment by wagenet** [comment]
@sergiotapia do you have Skylight enabled in the development environment? Skylight shouldn't have to be doing any curl'ing when it's not activated.

**Comment by sergiotapia** [comment]
@wagenet Yes we have Skylight enabled in dev and it's been working fine for months now. Are you saying to disable it? That doesn't really fix the issue though. :cry:

**Comment by wagenet** [comment]
@sergiotapia Running in development isn't normal operation so, if it's preventing you from doing essential things like migrating, disabling Skylight in development would be a reasonable _temporary_ measure until we can roll out a new agent with the fix. We hope to have the fix out next week.

I'm also a bit curious to hear more about why you're finding it useful to run Skylight in development mode. Would you be able to email support@skylight.io or click the "?" button in the online Skylight app and tell us a bit?

**Comment by wagenet** [comment]
We've just released v0.8.1 of the gem which should solve this issue.
